# Title     : TODO
# Objective : TODO
# Created by: Daniel Kec
# Created on: 15.10.19

# require(jsonlite)
# require(dplyr)
# require(ggplot2)
# require(lubridate)
# #theme_set(theme_bw())
#
# svgExample1 <- function(model) {
#     svg()
#     print(
#     ggplot(model, aes(time, ele, fill = ele)) + geom_col()
#     )
#     grDevices:::svg.off()
# }
#
# main <- function(arg){
#     df <- fromJSON(arg)$trkseg
#     cdf <- df[lubridate::year(df$time) %in% c(1967:2020), ]
#     print(head(cdf,10))
#     svgExample1(head(df,10))
# }

# Title     : TODO
# Objective : TODO
# Created by: Daniel Kec
# Created on: 15.10.19

# require(jsonlite)
# require(dplyr)
# require(ggplot2)

library(jsonlite)
library(ggplot2)
# library(lubridate)
# library(tibble)
# library(scales)
theme_set(theme_bw())

# Plots a simple bar chart of the brexit petition data and returns the SVG representation of the plot.
svgExample1 <- function(model) {
    svg()
    print(ggplot(model, aes(name, signature_count, fill = signature_count)) + geom_col())
    grDevices:::svg.off()
}

svgExample2 <- function(data) {
    #2019-10-13T13:20:19Z
    format <- "%Y-%m-%dT%H:%M:%S"
    # tidyData <- head(data,20)
    tidyData <- data
    tidyData$time <- as.POSIXct(tidyData$time,format=format,tz="UTC")
    tidyData$ele <- as.numeric(tidyData$ele)
    tidyData$lat <- as.numeric(tidyData$lat)
    tidyData$lon <- as.numeric(tidyData$lon)

    tidyData <- tidyData[order(tidyData$time),]

    print(head(tidyData,10))

    # test <- data.frame(date=seq(as.POSIXct("2019-10-13 00:00:00",tz="CET"),as.POSIXct("2019-10-14 00:00:00",tz="CET"),"hours" ),
    # value= runif(49) )

    svg()
    # plot
    print(
        # ggplot(tidyData, aes(x=time))
        # # + geom_line(aes(y=lat, fill="#f8766d"))
        # + geom_line(aes(y=ele, fill="#00ba38"))
        # + labs(caption="Generated by FastR")  # title and caption
        # # + scale_fill_manual(name="", values = c("psavert"="#00ba38", "elev"="#f8766d")) # line color
        # + theme(panel.grid.minor = element_blank())


        ggplot(data = tidyData) +
        geom_line(aes(x = time, y = ele), color = "#09557f", alpha = 0.6, size = 0.6) +
        theme_minimal()


        # ggplot() + geom_line(data=tidyData, aes(x=time, y=ele)) +
        # theme(text=element_text(size=16),
        # legend.text=element_text(size=16),
        # axis.text=element_text(size=16, colour="black"),
        # panel.background = element_rect(fill = 'white', colour = 'black'),
        # axis.title.y = element_text(size=16, vjust = 0.3),
        # axis.title.x = element_text(size=16, vjust = 0),
        # legend.key=element_rect(fill="white")) +
        # scale_x_datetime( breaks = date_breaks("2 hours"),
        # labels = date_format("%a-%d\n%H:%M", tz="CET"),
        # expand = c(0,0))


        # ggplot(tidyData, aes(x = time,y = ele)) + geom_line(colour = "red")

        # ggplot(tidyData, aes(x=time)) +
        # geom_line(aes(y=ele)) +
        # # labs(title="Monthly Time Series", subtitle="Returns Percentage from Economics Dataset", caption="Source: Economics", y="Returns %") +  # title and caption
        # #scale_x_date(labels = lbls, breaks = brks) +  # change to monthly ticks and labels
        # theme(axis.text.x = element_text(angle = 90, vjust=0.5), panel.grid.minor = element_blank())  # turn off minor grid
    )
    grDevices:::svg.off()
}

main <- function(arg){
    df <- fromJSON(arg)$trkseg
    #brexitByConstituency <-	brexit$data$attributes$signatures_by_constituency# %>% arrange(desc(signature_count))
    #print(head(brexitByConstituency,100))
    #svgExample1(head(brexitByConstituency,3))
    svgExample2(df)
    #return('ahoj');
}